language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  # The following copied from conda documentation.
  # This is done conditionally because it saves some downloading
  # if the version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n espei-env python=$TRAVIS_PYTHON_VERSION
  - source activate espei-env
  - conda install -c conda-forge 'espei==0.4.1' 'pycalphad==0.6.1'
before_script:
  - source activate espei-env
script:
  - python ./ci/dataset_linter.py --verbose
after_success:
  - ./ci/git-commit-changes.sh
notifications:
  email: False
env:
  global:
    secure: idtDuFAa4MMiVOPEBNrmHxeh8bwlVPbX0aWD5tDktvXnLtSmC/+htr4kOCgtYySoD/PTWy//JgtsgQ1du08ZB/cXfCTDQp8lZptNi8vmlgpGjNk0yfKoIRdIhTXa89fEPM+/ddioXvecK6I0u7Kgwf64BDdCjC7qEAUMC0Oio6dGx+EEwKFeuBTEOShmCOOzwlvbzgR6oYWa5OESDpAg+fypkCq/zboFBW3D3DwWaUtXAmZSW/UaKusV7p4H+DfA59mqXcNkZboB4MSMXwYTeBE8B2RIUhMlFQJ+VxfdTPtw5CNUDx1QBRvuJA7I7CDdVwR7hhjDemH68EbIv3AKlnDB4KHym28/JlRZXG3n3iJQmxI5uPdsz7YDQLO3/2GG+0KNzEBNEXR2JHzwUW+c5DRDrzcx+0nVdCYvcYQQt946mePBtnnlbZdWM3Ypz9L/AOPiK6BiHu2Z4/OCpepqo+AWvNLLW9ZSIRmiW8uZsvSgYWN8TueSLBkFcAGNE+jtYVk10XZoPO5GCvAeB73+toqTyhp7qEQUg8aI045TOGBxuZUneFNbk00n8wkzygJf+FjZbQyrxIbBls5b/Pv+l/bEi27L4FYhaqx6Hn8Ffd94SzYEmwGq7R4wKMPyHgHxgJEmNMZV8Hbime81uRwaVSP3aWrHwwX8ie5fausRNik=
